import fs from 'fs';

// Base64 encoded 1x1 blue pixel PNG as placeholder
const icon16 = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH5QEMFQoWJ8WzygAAACZJREFUOMtj/M9A/2AwGsBoAKMBjAYwGsBoAKMBjAYwGsBoAKMBAAC9mwQBdvqKqwAAAABJRU5ErkJggg==', 'base64');
const icon48 = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH5QEMFQsXJ8WzygAAACZJREFUaN7t0jEBAAAIAyC0f+duwlYMcNLEYDAYDAaDwWAwGAzGAD+5BQFB/8LyXgAAAABJRU5ErkJggg==', 'base64');
const icon128 = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH5QEMFQwHJ8WzygAAACZJREFUeNrtwQEBAAAAgiD/r25IQAEAAAAAAAAAAAAAAAAAAAAAgJcBSYAAAQ7qp7QAAAAASUVORK5CYII=', 'base64');

fs.writeFileSync('icon16.png', icon16);
fs.writeFileSync('icon48.png', icon48);
fs.writeFileSync('icon128.png', icon128);

console.log('Created placeholder icons');